<template>
  <div class="h-screen flex flex-col bg-gray-100">
    <!-- PDF Page Header -->
    <div class="bg-white shadow-sm px-6 py-4 flex items-center justify-between">
      <div class="flex items-center space-x-4">
        <el-button @click="goBack" type="text">
          <i class="fas fa-arrow-left mr-2"></i>
          Back to Data Manager
        </el-button>
        <div class="h-6 w-px bg-gray-300"></div>
        <h1 class="text-xl font-semibold text-gray-900">{{ reportTitle }}</h1>
      </div>
      <div class="flex items-center space-x-3">
        <el-button type="primary">
          <i class="fas fa-download mr-2"></i>
          Download PDF
        </el-button>
        <el-button type="default">
          <i class="fas fa-print mr-2"></i>
          Print
        </el-button>
      </div>
    </div>

    <!-- PDF Content -->
    <div class="flex-1 p-6 overflow-auto">
      <div class="max-w-4xl mx-auto bg-white shadow-lg rounded-lg">
        <!-- PDF Header -->
        <div class="bg-primary text-white p-8 rounded-t-lg">
          <div class="flex items-center justify-between">
            <div>
              <h1 class="text-3xl font-bold mb-2">{{ gene }} Analysis Report</h1>
              <p class="opacity-90">{{ disease }} Research - Generated on {{ analysisDate }}</p>
            </div>
            <div class="text-right">
              <div class="text-2xl font-bold">Y150</div>
              <div class="text-sm opacity-90">Genomics Platform</div>
            </div>
          </div>
        </div>

        <!-- PDF Body -->
        <div class="p-8">
          <!-- Executive Summary -->
          <div class="mb-8">
            <h2 class="text-2xl font-bold text-gray-900 mb-4">Executive Summary</h2>
            <div class="bg-gray-50 p-6 rounded-lg">
              <div class="grid grid-cols-2 gap-6 mb-4">
                <div>
                  <h3 class="font-semibold text-gray-700">Target Gene</h3>
                  <p class="text-lg text-gray-900">{{ gene }}</p>
                </div>
                <div>
                  <h3 class="font-semibold text-gray-700">Disease Context</h3>
                  <p class="text-lg text-gray-900">{{ disease }}</p>
                </div>
                <div>
                  <h3 class="font-semibold text-gray-700">Analysis Date</h3>
                  <p class="text-lg text-gray-900">{{ analysisDate }}</p>
                </div>
                <div>
                  <h3 class="font-semibold text-gray-700">Status</h3>
                  <el-tag :type="status === 'Completed' ? 'success' : 'warning'" size="large">
                    {{ status }}
                  </el-tag>
                </div>
              </div>
              <p class="text-gray-700">
                This comprehensive analysis examines the role of {{ gene }} in {{ disease }} pathogenesis, 
                therapeutic targeting opportunities, and clinical implications based on multi-omics data integration.
              </p>
            </div>
          </div>

          <!-- Key Findings -->
          <div class="mb-8">
            <h2 class="text-2xl font-bold text-gray-900 mb-4">Key Findings</h2>
            <div class="space-y-4">
              <div class="bg-blue-50 border-l-4 border-blue-400 p-4">
                <h3 class="font-semibold text-blue-900">Expression Profile</h3>
                <p class="text-blue-800">{{ gene }} shows significant differential expression in {{ disease }} samples compared to normal controls (p &lt; 0.001).</p>
              </div>
              <div class="bg-green-50 border-l-4 border-green-400 p-4">
                <h3 class="font-semibold text-green-900">Pathway Analysis</h3>
                <p class="text-green-800">Enrichment analysis reveals involvement in key cancer pathways including cell cycle regulation and apoptosis.</p>
              </div>
              <div class="bg-purple-50 border-l-4 border-purple-400 p-4">
                <h3 class="font-semibold text-purple-900">Clinical Correlation</h3>
                <p class="text-purple-800">High {{ gene }} expression correlates with improved treatment response and overall survival.</p>
              </div>
            </div>
          </div>

          <!-- Footer -->
          <div class="border-t pt-6 text-center text-gray-500">
            <p>Generated by Y150 Genomics Platform | © 2024 | Report ID: {{ reportId }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'

const route = useRoute()
const router = useRouter()

const reportId = ref('')
const gene = ref('EGFR')
const disease = ref('Lung Cancer')
const status = ref('Completed')
const analysisDate = ref('2024-03-15')

const reportTitle = computed(() => `${gene.value} Analysis Report`)

onMounted(() => {
  reportId.value = route.params.reportId || 'EGFR-Lung-Cancer-20240315'
  
  if (reportId.value) {
    const parts = reportId.value.split('-')
    if (parts.length >= 3) {
      gene.value = parts[0]
      disease.value = parts.slice(1, -1).join(' ')
    }
  }
})

const goBack = () => {
  router.push('/manager')
}
</script>

<style scoped>
.bg-primary {
  background-color: #83a594;
}

:deep(.el-button--primary) {
  background-color: #83a594;
  border-color: #83a594;
}

:deep(.el-button--primary:hover) {
  background-color: #519294;
  border-color: #519294;
}
</style> 